# Generated by Django 6.0.3 on 2026-03-19 22:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bike_routes',
            new_name='bike_route',
        ),
        migrations.RenameModel(
            old_name='bookings',
            new_name='booking',
        ),
    ]
