# Generated by Django 6.0.3 on 2026-03-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_rename_bike_routes_bike_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_date',
            field=models.DateField(default=None),
        ),
    ]
