# Generated by Django 6.0.3 on 2026-03-22 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_tour_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bike_route',
            new_name='BikeRoute',
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_date',
            field=models.DateField(),
        ),
    ]
