# Generated by Django 6.0.3 on 2026-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_rename_bike_route_bikeroute_alter_tour_tour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_bookings',
            field=models.ManyToManyField(related_name='tours', to='tours.booking'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_routes',
            field=models.ManyToManyField(related_name='tours', to='tours.bikeroute'),
        ),
    ]
