# Generated by Django 6.0.3 on 2026-04-03 23:51

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_user_alter_bikeroute_user_alter_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_bookings',
            field=models.ManyToManyField(help_text='Hold alt to select multiple routes', related_name='tours', to='tours.booking'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_routes',
            field=models.ManyToManyField(help_text='Hold alt to select multiple routes', related_name='tours', to='tours.bikeroute'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_description', models.CharField(max_length=255)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='./media'), upload_to='images')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
