# Generated by Django 6.0.3 on 2026-04-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tour_tour_bookings_alter_tour_tour_routes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_bookings',
            field=models.ManyToManyField(help_text='Hold alt to select multiple bookings', related_name='tours', to='tours.booking'),
        ),
    ]
