# Generated by Django 6.0.3 on 2026-05-01 21:55

import datetime
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='post',
            field=models.CharField(verbose_name=django.db.models.fields.TextField),
        ),
        migrations.AlterField(
            model_name='forum',
            name='time_posted',
            field=models.DateField(default=datetime.date(2026, 5, 1)),
        ),
    ]
