# Generated by Django 6.0.3 on 2026-05-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_forum_post_alter_forum_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='post',
            field=models.TextField(),
        ),
    ]
