# Generated by Django 6.0.3 on 2026-05-01 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_forum_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='time_posted',
            field=models.DateField(default=datetime.datetime(2026, 5, 2, 0, 14, 39, 687441)),
        ),
    ]
