# Generated by Django 6.0.3 on 2026-05-18 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_alter_forum_time_posted_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
